# Netflix Show Data Analysis

## Project objective
#### The objective of this project is to find insights for content growth,regional distribution and target audience, and how netflix content has been evolved through the year.

### Importing important libraries to perform analysis.

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Loading Dataset

In [20]:
df = pd.read_csv("netflix_titles.csv")
df.head(4)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."

Making minor corrections for better readability

In [22]:
df.rename(columns={'show_id' :'Show_Number','title':'Title','type':'Show_Type','director':'Director','cast':'Cast','country':'Country','date_added':'Date_added','release_year':'Release_Year','rating':'Rating','duration':'Duration','listed_in':'Listed_In','description':'Description'}, inplace=True)
df.head(4)

,Show_Number,Show_Type,Title,Director,Cast,Country,Date_added,Release_Year,Rating,Duration,Listed_In,Description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."

## Data cleaning and handling the missing values.

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Show_Number   8807 non-null   object
 1   Show_Type     8807 non-null   object
 2   Title         8807 non-null   object
 3   Director      6173 non-null   object
 4   Cast          7982 non-null   object
 5   Country       7976 non-null   object
 6   Date_added    8797 non-null   object
 7   Release_Year  8807 non-null   int64
 8   Rating        8803 non-null   object
 9   Duration      8804 non-null   object
 10  Listed_In     8807 non-null   object
 11  Description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [24]:
df.describe(include='all')

,Show_Number,Show_Type,Title,Director,Cast,Country,Date_added,Release_Year,Rating,Duration,Listed_In,Description
count,8807,8807,8807,6173,7982,7976,8797,8807.000000,8803,8804,8807,8807
unique,8807,2,8807,4528,7692,748,1767,NaN,17,220,514,8775
top,s1,Movie,Dick Johnson Is Dead,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",NaN,TV-MA,1 Season,"Dramas, International Movies","Paranormal activity at a lush, abandoned prope..."
freq,1,6131,1,19,19,2818,109,NaN,3207,1793,362,4
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.180198,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.819312,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1925.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,NaN,NaN

In [25]:
df['Country'] = df['Country'].fillna('Unknown')
df['Director'] = df['Director'].fillna('Unknown')
df['Cast'] = df['Cast'].fillna('Unknown')
df = df.dropna(subset=['Rating'])

In [27]:
df.isnull().sum()

Show_Number      0
Show_Type        0
Title            0
Director         0
Cast             0
Country          0
Date_added      10
Release_Year     0
Rating           0
Duration         3
Listed_In        0
Description      0
dtype: int64

In [35]:
df['Date_added'] = pd.to_datetime(df['Date_added'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8702 entries, 0 to 8806
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Show_Number   8702 non-null   object
 1   Show_Type     8702 non-null   object
 2   Title         8702 non-null   object
 3   Director      8702 non-null   object
 4   Cast          8702 non-null   object
 5   Country       8702 non-null   object
 6   Date_added    8702 non-null   datetime64[ns]
 7   Release_Year  8702 non-null   int64
 8   Rating        8702 non-null   object
 9   Duration      8702 non-null   object
 10  Listed_In     8702 non-null   object
 11  Description   8702 non-null   object
 12  Duration_int  8702 non-null   int64
dtypes: datetime64[ns](1), int64(2), object(10)
memory usage: 951.8+ KB

In [36]:
df['Rating'] = df.groupby('Show_Type')['Rating'].transform(lambda x: x.fillna(x.mode()[0]))
df.isnull().sum()

Show_Number     0
Show_Type       0
Title           0
Director        0
Cast            0
Country         0
Date_added      0
Release_Year    0
Rating          0
Duration        0
Listed_In       0
Description     0
Duration_int    0
dtype: int64

In [37]:
df = df.dropna(subset=['Duration'])
df = df.dropna(subset=['Date_added'])
df = df.dropna(subset=['Rating'])
df['Duration_int'] = df['Duration'].str.extract('(\\d+)').astype(int)
df.head()

,Show_Number,Show_Type,Title,Director,Cast,Country,Date_added,Release_Year,Rating,Duration,Listed_In,Description,Duration_int
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",90
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,1
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",1
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2

In [38]:
df.isnull().sum()

Show_Number     0
Show_Type       0
Title           0
Director        0
Cast            0
Country         0
Date_added      0
Release_Year    0
Rating          0
Duration        0
Listed_In       0
Description     0
Duration_int    0
dtype: int64